# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "ricoshot"
mod.name = "Ricoshot"
mod.group = "zigqora.ricoshot"
mod.version = "1.0.0"

deps.fabric_loader = "0.19.2"
loomx.loom_version = "1.16-SNAPSHOT"

["1.21.1"]
mod.mc_compat = ">=1.21 <1.21.4"
mod.mc_releases = ["1.21", "1.21.1", "1.21.2", "1.21.3"]

deps.fabric_api = "0.116.10+1.21.1"
deps.yarn_mappings = "1.21.1+build.3"

["1.21.4"]
mod.mc_compat = ">=1.21.4 <1.21.11"
mod.mc_releases = ["1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10"]

deps.fabric_api = "0.119.4+1.21.4"
deps.yarn_mappings = "1.21.4+build.8"

["1.21.11"]
mod.mc_compat = ">=1.21.11 <1.22"
mod.mc_releases = ["1.21.11"]

deps.fabric_api = "0.141.4+1.21.11"
deps.yarn_mappings = "1.21.11+build.6"
